### ISSUE TITLE
Plugin only shows some of my folders

### ISSUE THREAD

**Issue by ghost** [hegerdes/joplin-plugin-remote-note-pull#4]
**Describe the bug**
I have some hundreds of folders and subfolders, it seems that the plugin only shows about 100 of them? I cannot choose the folder that I would prefer to sync to under options or when trying to create a new sync note.

**To Reproduce**
1. Go to **options**
2. Click on **RemoteMarkdownSync**
3. Click on the field called **select default notebook**

**Expected behavior**
It should be possible to see all folders or search for folders

**Version(please complete the following information):**
 - OS: Arch Linux 6.6.10
 - Joplin Version:  2.13.13
 - Plugin Version:  1.1.3

**Comment by hegerdes** [comment]
Hi, thanks for raising this. I will look into it.

Since I don't have that many notebooks can you please add an screenshot? Does this only happen in the settings for the `default notebook` or also when creating a new sync note (when you have the notebook drop-down)? Exactly 100?

It might be likely that the joplin internal api has a limit of returned notebooks at one request and currently there is no pagination for implemented in the client.

**Comment by ghost** [comment]
I suspect your a right that it is something internal to joplin. I tried counting, and it does seem to be **exactly 100**.

As to exactly which notebooks are shown up, it seems to be somewhat random, but perhaps it has to do with how joplin internally organizing notebooks? It is always the same notebook even if I create new ones. I can scroll for quite a bit, but it only shows a small number of the notes I have.

It happens both in setting and when trying to create a new sync note.

From "settings" page:
![Screenshot_20240112_202029](https://github.com/hegerdes/joplin-plugin-remote-note-pull/assets/40796214/b3461a42-7a0d-4cfa-bf3a-9712f2a4f12f)

Creating a new sync note:
![Screenshot_20240112_202546](https://github.com/hegerdes/joplin-plugin-remote-note-pull/assets/40796214/bcb9732b-2930-4211-8116-530b8ff3f2d6)

Example of a few notebooks (with subnotebooks) that never show up:
![Screenshot_20240112_202631](https://github.com/hegerdes/joplin-plugin-remote-note-pull/assets/40796214/19194895-fe62-411d-9599-452c3918cca7)

**Comment by hegerdes** [comment]
Added a PR that fixes it. But also found another small bug. 

Will release new version on sundry or monday

**Comment by hegerdes** [comment]
Is released - update should be picked up by Joplins store in a couple of hours.
