### ISSUE TITLE
repo's About section has a typo

### ISSUE THREAD

**Issue by taw00** [hegerdes/joplin-plugin-remote-note-pull#7]
This is not an issue with the code or plugin, but with this github repo's metadata:

"This Plugin can create a new Note ***form*** any Website and watches the site for changes."    
… should be …  
"This Plugin can create a new Note ***from*** any Website and watches the site for changes."

I.e., "form" should be "from"

Have a lovely day. :)
-t

**Comment by hegerdes** [comment]
Hey, thanks for pointing this out 😊

Sometimes I'm a bit sloppy when typing. I'm quiet sure there are more typos in the code and docs. I will fix then when I stumble on them,
